(function(){ /* JS identical to previous delivered build; opens drawer on click, native sort, ajax apply/clear. */
if(window.__VFS_INIT__) return; window.__VFS_INIT__=true;
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
const state={sort:'inspire',filters:{},selectedCount:0};
function openDrawer(w){if(!w)return;w.classList.add('is-open');w.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');}
function closeDrawer(w){if(!w)return;w.classList.remove('is-open');w.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll');}
function safeJSON(r){const ct=r.headers.get('content-type')||'';if(!r.ok)return{success:false,html:''};if(ct.includes('application/json'))return r.json();return{success:false,html:''};}
function renderCount(n){const c=$('#filterCount');if(c)c.textContent=`(${n})`;}
function collectFilters(root){const f={};f.location=$$('.pill.is-selected',root).map(p=>p.getAttribute('data-term'));f.capacity=$$('input[name=\"capacity[]\"]:checked',root).map(i=>i.value);f.venueType=$$('input[name=\"venueType[]\"]:checked',root).map(i=>i.value);f.features=$$('input[name=\"features[]\"]:checked',root).map(i=>i.value);f.style=$$('input[name=\"style[]\"]:checked',root).map(i=>i.value);const n=f.location.length+f.capacity.length+f.venueType.length+f.features.length+f.style.length;state.selectedCount=n;renderCount(n);return f;}
function dispatchApply(){const url=window.vfsData&&window.vfsData.ajax_url;if(!url)return;const fd=new FormData();fd.append('action','vfs_filter_venues');fd.append('filters',JSON.stringify(state.filters||{}));fd.append('sort',state.sort||'inspire');fd.append('_ajax_nonce',(window.vfsData&&window.vfsData.nonce)||'');fetch(url,{method:'POST',credentials:'same-origin',body:fd}).then(safeJSON).then(json=>{const list=document.getElementById('vfs-venue-list');if(list&&json&&json.success){list.innerHTML=json.html||'';}}).catch(console.error);}
function attachNativeSort(){const sel=$('#sortSelect');if(!sel)return;const map={'inspire':'inspire','az':'az','za':'za','popular':'newest','latest':'newest','newest':'newest','oldest':'oldest','price_low':'price_low','price_high':'price_high'};state.sort=map[sel.value]||'inspire';sel.addEventListener('change',()=>{const v=sel.value;state.sort=map[v]||'inspire';dispatchApply();});}
function attachDrawer(){const wrap=document.getElementById('filter-drawer');if(!wrap)return;const panel=wrap.querySelector('.fdrawer__panel');$$('[aria-controls=\"filter-drawer\"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openDrawer(wrap);}));$('.fdrawer__backdrop',wrap)?.addEventListener('click',e=>{e.preventDefault();closeDrawer(wrap);});panel.querySelector('.close-link')?.addEventListener('click',e=>{e.preventDefault();closeDrawer(wrap);});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer(wrap);});$$('.row',panel).forEach(r=>r.addEventListener('click',()=>{const open=r.classList.toggle('open');r.setAttribute('aria-expanded',open?'true':'false');const pan=r.nextElementSibling;pan?.setAttribute('aria-hidden',open?'false':'true');}));panel.addEventListener('change',()=>{state.filters=collectFilters(panel);});panel.addEventListener('click',e=>{const pill=e.target.closest('.pill');if(!pill)return;pill.classList.toggle('is-selected');state.filters=collectFilters(panel);});$('#applyBtn',panel)?.addEventListener('click',e=>{e.preventDefault();state.filters=collectFilters(panel);dispatchApply();closeDrawer(wrap);});$('#clearAll',panel)?.addEventListener('click',e=>{e.preventDefault();$$('input[type=\"checkbox\"]',panel).forEach(i=>i.checked=false);$$('.pill.is-selected',panel).forEach(p=>p.classList.remove('is-selected'));state.filters={};renderCount(0);dispatchApply();closeDrawer(wrap);});}
function attachFilterbarClear(){$('#clearFilters')?.addEventListener('click',e=>{e.preventDefault();const panel=$('#filter-drawer .fdrawer__panel');if(!panel)return;$$('input[type=\"checkbox\"]',panel).forEach(i=>i.checked=false);$$('.pill.is-selected',panel).forEach(p=>p.classList.remove('is-selected'));state.filters={};renderCount(0);dispatchApply();});}
function attachFinderForm(){document.getElementById('finderForm')?.addEventListener('submit',(e)=>{e.preventDefault();const data={location:document.getElementById('fLocation').value,capacity:document.getElementById('fCapacity').value,type:document.getElementById('fType').value,features:document.getElementById('fFeatures').value,style:document.getElementById('fStyle').value};console.log('Finder submit:',data);// Hook this to your search/filter logic as needed});}
function init(){attachNativeSort();attachDrawer();attachFilterbarClear();attachFinderForm();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init,{once:true});}else{init();}
})();
